Update README.md
T-Yashiro51/team_kanri_app2 pull request #1
Opened 2024-08-08 07:42 UTC by T-Yashiro51

新しいリポジトリを作成しました。

2024-08-08 10:58 UTC, busitora requested changes

2024-08-08 10:58 UTC, busitora commented on README.md
> +■ ユーザー層について SEOやFacebookなどのSNSでの広告を検討しています。
具体的にどういった層になりますか?

2024-08-08 10:58 UTC, busitora commented on README.md
> +■機能の実現構想
こちらを埋めていただいてよろしいでしょうか？

2024-08-08 11:33 UTC, T-Yashiro51 commented on README.md
> +■ ユーザー層について SEOやFacebookなどのSNSでの広告を検討しています。
学童野球を中心に、ボランティアのクラブチームを軸に考えております。

2024-08-08 11:36 UTC, T-Yashiro51 commented on README.md
> +■機能の実現構想
追記しましたが、現状CRUDのみで検討しております。

2024-08-09 05:28 UTC, Tsuchiya2 commented
対応ありがとうございます。
以下コメントになります。

---

■ ユーザー層について：どんなユーザー層なのかを記載する箇所に「SEOやFacebookなどのSNSでの広告を検討しています。」とユーザーの獲得内容が書かれており、項目と記載内容がバラバラになっています。

■サービスの利用イメージ：実際に使った際のイメージを読み手に分かるように、もう少し詳しくREADMEに記載してください。

■機能候補 
・ログイン・管理者権限を除くと「ファイルの共有」のみがMVPとなっていますが、スケジュール管理＆共有はMVPに含めなくても大丈夫そうでしょうか。「ファイルの共有」のみでサービスのどんなことが検証できるのかをREADMEに記載してください。

■機能の実現構想
・詳しく内容を記載してください。

2024-08-13 08:05 UTC, T-Yashiro51 commented
・ユーザー層について
・サービスの利用イメージ
・機能候補
・機能の実現構想
上記4点追記いたしました。

2024-08-13 12:06 UTC, rdhdchloe commented
ありがとうございます。
以下コメントになります。

---

#### サービスの利用イメージ
`スケジュール調整・共有`
→ スケジュールをどうやって調整、共有されますか？フローを教えてください
`LINE通知`
→ どんな通知を送る・受け取るですか？
`ファイル共有`
→ どんなファイルか、どうやって共有するか、共有されるまでのフローを教えていただきたいです。

#### 機能の実現構想
ファイルの保存や共有など、スケジュールの共有
→共有についてもう少し詳しく追記していただきたいです。また、どういった技術で実現可能かを追記していただきたいです。

よろしくお願い致します！

2024-08-14 22:50 UTC, T-Yashiro51 commented
・サービスの利用イメージ
・機能の実現構想
を追加・修正いたしました。

2024-08-15 02:36 UTC, Tsuchiya2 commented
概ね良いかと思います。LGTMです。

2024-08-15 06:45 UTC, merged